spring:
  application:
    name: ${APP_NAME:backend-service}

server:
  port: ${SERVER_PORT:8082}

services:
  database:
    url: ${DATABASE_SERVICE_URL:http://database-service:8081}

logging:
  level:
    org.springframework.web: DEBUG
